import { createLiteModel } from "../storage/liteModel.js";

export const RecommendAuthorProfile = createLiteModel({
  modelName: "RecommendAuthorProfile",
  tableName: "recommend_author_profiles",
  uniqueFields: ["authorKey"],
  defaults: {
    authorKey: "",
    authorUid: "",
    authorSecUid: "",
    authorUniqueId: "",
    authorShortId: "",
    authorNickname: "",
    authorAvatar: "",
    authorSignature: "",
    authorCustomVerify: "",
    authorEnterpriseVerifyReason: "",
    authorVerificationType: 0,
    userUrl: "",
    followingCount: 0,
    followerCount: 0,
    totalFavorited: 0,
    awemeCount: 0,
    userAge: null,
    gender: "unknown",
    ipLocation: "",
    country: "",
    province: "",
    city: "",
    district: "",
    firstSeenAt: null,
    lastSeenAt: null,
    seenWorkCount: 0,
    seenExposureCount: 0,
    sampleWorkIds: [],
    topTopics: [],
    topKeywords: [],
    rawAuthorJson: {},
  },
});
