import { createLiteModel } from "../storage/liteModel.js";

export const RecommendWork = createLiteModel({
  modelName: "RecommendWork",
  tableName: "recommend_works",
  uniqueFields: ["awemeId"],
  defaults: {
    awemeId: "",
    workUrl: "",
    workType: "unknown",
    sourceType: "recommend",
    title: "",
    desc: "",
    topics: [],
    images: [],
    videoCover: "",
    videoAddr: "",
    musicAddr: "",
    publishAt: null,
    durationSeconds: 0,
    admireCount: 0,
    diggCount: 0,
    commentCount: 0,
    collectCount: 0,
    shareCount: 0,
    ipLocation: "",
    authorKey: "",
    authorUid: "",
    authorSecUid: "",
    authorUniqueId: "",
    authorShortId: "",
    authorNickname: "",
    authorAvatar: "",
    authorSignature: "",
    authorCustomVerify: "",
    authorEnterpriseVerifyReason: "",
    authorVerificationType: 0,
    userUrl: "",
    followingCount: 0,
    followerCount: 0,
    totalFavorited: 0,
    awemeCount: 0,
    userAge: null,
    gender: "unknown",
    firstSeenAt: null,
    lastSeenAt: null,
    seenCount: 0,
    country: "",
    province: "",
    city: "",
    district: "",
    lastRunId: "",
    latestExposureId: "",
    latestAnalysisScore: 0,
    latestAnalysisAt: null,
    rawDetailJson: {},
  },
});
