import { createLiteModel } from "../storage/liteModel.js";

export const Work = createLiteModel({
  modelName: "Work",
  tableName: "works",
  uniqueFields: ["awemeId"],
  defaults: {
    awemeId: "",
    workUrl: "",
    workType: "unknown",
    discoverySource: "",
    sourceLabel: "",
    title: "",
    desc: "",
    authorName: "",
    authorAvatar: "",
    userUrl: "",
    userId: "",
    authorSecUid: "",
    userDesc: "",
    keywordSource: "",
    topics: [],
    images: [],
    videoCover: "",
    videoAddr: "",
    admireCount: 0,
    diggCount: 0,
    commentCount: 0,
    collectCount: 0,
    shareCount: 0,
    followingCount: 0,
    followerCount: 0,
    totalFavorited: 0,
    awemeCount: 0,
    publishAt: null,
    userAge: null,
    gender: "unknown",
    ipLocation: "",
    recommendSeenCount: 0,
    recommendLastSeenAt: null,
    status: "new",
    rawJson: {},
    discoveredAt: null,
    lastCollectedAt: null,
  },
});
